// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdRiDADyBQMMYtI0nYGcpR7QA8Ha3z7sU',
    appId: '1:1083237536747:web:cf09352f68752f6b46bfae',
    messagingSenderId: '1083237536747',
    projectId: 'chat-app-6e4c1',
    authDomain: 'chat-app-6e4c1.firebaseapp.com',
    storageBucket: 'chat-app-6e4c1.appspot.com',
    measurementId: 'G-20X7YB6250',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs_5fi6BzZAVayp10EvGqhIOOKFuv4xps',
    appId: '1:1083237536747:android:f145f323f06755c146bfae',
    messagingSenderId: '1083237536747',
    projectId: 'chat-app-6e4c1',
    storageBucket: 'chat-app-6e4c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvmG_M4BhLFTvclZ9TIrZGbPQ3WH_IIOg',
    appId: '1:1083237536747:ios:eb159b6c77d43e4646bfae',
    messagingSenderId: '1083237536747',
    projectId: 'chat-app-6e4c1',
    storageBucket: 'chat-app-6e4c1.appspot.com',
    iosBundleId: 'com.example.flutterChatAppMongo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvmG_M4BhLFTvclZ9TIrZGbPQ3WH_IIOg',
    appId: '1:1083237536747:ios:eb159b6c77d43e4646bfae',
    messagingSenderId: '1083237536747',
    projectId: 'chat-app-6e4c1',
    storageBucket: 'chat-app-6e4c1.appspot.com',
    iosBundleId: 'com.example.flutterChatAppMongo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdRiDADyBQMMYtI0nYGcpR7QA8Ha3z7sU',
    appId: '1:1083237536747:web:15f23e8520a413cb46bfae',
    messagingSenderId: '1083237536747',
    projectId: 'chat-app-6e4c1',
    authDomain: 'chat-app-6e4c1.firebaseapp.com',
    storageBucket: 'chat-app-6e4c1.appspot.com',
    measurementId: 'G-QGYTLYVE3V',
  );
}
